/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-08-06 04:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.text.SimpleDateFormat;
import java.io.*;
import java.util.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import com.google.gson.*;
import java.text.SimpleDateFormat;

public final class list_002dsites_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


/**
 * CMS 콘텐츠 저장을 위한 파일 유틸리티 클래스
 * JSP 내에서 사용하는 정적 메서드들을 제공
 */
public class FileUtils {
    
    private final String GENERATED_CONTENT_PATH = "generated-content";
    private final String ENCODING = "UTF-8";
    private final Gson gson = new GsonBuilder().setPrettyPrinting().create();
    
    /**
     * 사이트 폴더 경로 생성
     */
    public String getSitePath(ServletContext context, String siteId) {
        String basePath = context.getRealPath("/");
        return basePath + File.separator + GENERATED_CONTENT_PATH + File.separator + siteId;
    }
    
    /**
     * 메뉴 콘텐츠 폴더 경로 생성
     */
    public String getContentPath(ServletContext context, String siteId, String menuId, String submenuId) {
        String sitePath = getSitePath(context, siteId);
        return sitePath + File.separator + menuId + File.separator + submenuId;
    }
    
    /**
     * 폴더 생성 (재귀적)
     */
    public boolean createDirectories(String path) {
        try {
            File directory = new File(path);
            if (!directory.exists()) {
                return directory.mkdirs();
            }
            return true;
        } catch (Exception e) {
            System.err.println("디렉토리 생성 실패: " + path + " - " + e.getMessage());
            return false;
        }
    }
    
    /**
     * 텍스트 파일 저장
     */
    public  boolean saveTextFile(String filePath, String content) {
        try {
            File file = new File(filePath);
            File parentDir = file.getParentFile();
            if (parentDir != null && !parentDir.exists()) {
                parentDir.mkdirs();
            }
            
            try (FileWriter writer = new FileWriter(file, StandardCharsets.UTF_8)) {
                writer.write(content);
                return true;
            }
        } catch (Exception e) {
            System.err.println("파일 저장 실패: " + filePath + " - " + e.getMessage());
            return false;
        }
    }
    
    /**
     * 텍스트 파일 읽기
     */
    public String readTextFile(String filePath) {
        try {
            File file = new File(filePath);
            if (!file.exists()) {
                return null;
            }
            
            StringBuilder content = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(file, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n");
                }
            }
            return content.toString();
        } catch (Exception e) {
            System.err.println("파일 읽기 실패: " + filePath + " - " + e.getMessage());
            return null;
        }
    }
    
    /**
     * JSON 파일 저장
     */
    public  boolean saveJsonFile(String filePath, Object data) {
        try {
            String jsonContent = gson.toJson(data);
            return saveTextFile(filePath, jsonContent);
        } catch (Exception e) {
            System.err.println("JSON 파일 저장 실패: " + filePath + " - " + e.getMessage());
            return false;
        }
    }
    
    /**
     * JSON 파일 읽기
     */
    public   Map<String, Object> readJsonFile(String filePath) {
        try {
            String content = readTextFile(filePath);
            if (content == null || content.trim().isEmpty()) {
                return null;
            }
            
            return gson.fromJson(content, Map.class);
        } catch (Exception e) {
            System.err.println("JSON 파일 읽기 실패: " + filePath + " - " + e.getMessage());
            return null;
        }
    }
    
    /**
     * 사이트 정보 객체 생성
     */
    public   Map<String, Object> createSiteInfo(String siteId, String siteName, String domain) {
        Map<String, Object> siteInfo = new HashMap<>();
        siteInfo.put("siteId", siteId);
        siteInfo.put("siteName", siteName);
        siteInfo.put("domain", domain);
        siteInfo.put("theme", "academic");
        siteInfo.put("language", "ko");
        siteInfo.put("createdAt", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").format(new Date()));
        siteInfo.put("lastUpdated", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").format(new Date()));
        return siteInfo;
    }
    
    /**
     * 콘텐츠 메타데이터 객체 생성
     */
    public   Map<String, Object> createContentMetadata(String pageId, String title, String subtitle, 
                                                           String mainContent, String features, double processingTime) {
        Map<String, Object> metadata = new HashMap<>();
        metadata.put("pageId", pageId);
        metadata.put("timestamp", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").format(new Date()));
        
        // 콘텐츠 정보
        Map<String, Object> content = new HashMap<>();
        content.put("title", title);
        content.put("subtitle", subtitle);
        content.put("mainContent", parseJsonArray(mainContent));
        content.put("features", parseJsonArray(features));
        content.put("images", new ArrayList<>());
        content.put("metadata", new HashMap<>());
        metadata.put("content", content);
        
        // 생성 정보
        Map<String, Object> generationInfo = new HashMap<>();
        generationInfo.put("model", "gpt-4");
        generationInfo.put("processingTime", processingTime);
        generationInfo.put("wordCount", calculateWordCount(title, subtitle, mainContent, features));
        metadata.put("generationInfo", generationInfo);
        
        return metadata;
    }
    
    /**
     * JSON 배열 문자열을 List로 파싱
     */
    private      List<Object> parseJsonArray(String jsonStr) {
        try {
            if (jsonStr == null || jsonStr.trim().isEmpty()) {
                return new ArrayList<>();
            }
            return gson.fromJson(jsonStr, List.class);
        } catch (Exception e) {
            // JSON 파싱 실패 시 단순 문자열로 처리
            List<Object> result = new ArrayList<>();
            result.add(jsonStr);
            return result;
        }
    }
    
    /**
     * 단어 수 계산
     */
    private int calculateWordCount(String title, String subtitle, String mainContent, String features) {
        int totalChars = 0;
        
        if (title != null) totalChars += title.length();
        if (subtitle != null) totalChars += subtitle.length();
        if (mainContent != null) totalChars += mainContent.length();
        if (features != null) totalChars += features.length();
        
        return totalChars;
    }
    
    /**
     * 파일 존재 여부 확인
     */
    public boolean fileExists(String filePath) {
        return new File(filePath).exists();
    }
    
    /**
     * 폴더 내 모든 사이트 목록 조회
     */
    public   List<String> listSites(ServletContext context) {
        List<String> sites = new ArrayList<>();
        try {
            String basePath = context.getRealPath("/") + File.separator + GENERATED_CONTENT_PATH;
            File baseDir = new File(basePath);
            
            if (baseDir.exists() && baseDir.isDirectory()) {
                File[] siteDirs = baseDir.listFiles(File::isDirectory);
                if (siteDirs != null) {
                    for (File siteDir : siteDirs) {
                        sites.add(siteDir.getName());
                    }
                }
            }
        } catch (Exception e) {
            System.err.println("사이트 목록 조회 실패: " + e.getMessage());
        }
        return sites;
    }
    
    /**
     * 사이트 내 메뉴 목록 조회
     */
    public List<String> listMenus(ServletContext context, String siteId) {
        List<String> menus = new ArrayList<>();
        try {
            String sitePath = getSitePath(context, siteId);
            File siteDir = new File(sitePath);
            
            if (siteDir.exists() && siteDir.isDirectory()) {
                File[] menuDirs = siteDir.listFiles(file -> 
                    file.isDirectory() && !file.getName().equals("site-info.json")
                );
                if (menuDirs != null) {
                    for (File menuDir : menuDirs) {
                        menus.add(menuDir.getName());
                    }
                }
            }
        } catch (Exception e) {
            System.err.println("메뉴 목록 조회 실패: " + e.getMessage());
        }
        return menus;
    }
    
    /**
     * 응답 JSON 생성 (성공)
     */
    public   String createSuccessResponse(String message, Object data) {
        Map<String, Object> response = new HashMap<>();
        response.put("success", true);
        response.put("message", message);
        response.put("data", data);
        response.put("timestamp", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").format(new Date()));
        return gson.toJson(response);
    }
    
    /**
     * 응답 JSON 생성 (실패)
     */
    public   String createErrorResponse(String message, String error) {
        Map<String, Object> response = new HashMap<>();
        response.put("success", false);
        response.put("message", message);
        response.put("error", error);
        response.put("timestamp", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").format(new Date()));
        return gson.toJson(response);
    }
    
    /**
     * 안전한 파일명 생성 (특수문자 제거)
     */
    public  String sanitizeFileName(String fileName) {
        if (fileName == null) return "untitled";
        return fileName.replaceAll("[^a-zA-Z0-9가-힣._-]", "_");
    }
    
    /**
     * 폴더 크기 계산 (바이트)
     */
    public   long calculateDirectorySize(String dirPath) {
        try {
            File directory = new File(dirPath);
            return Files.walk(directory.toPath())
                    .filter(Files::isRegularFile)
                    .mapToLong(path -> {
                        try {
                            return Files.size(path);
                        } catch (Exception e) {
                            return 0L;
                        }
                    })
                    .sum();
        } catch (Exception e) {
            return 0L;
        }
    }
    
    /**
     * 데이터 베이스 경로 생성 (/data/)
     * JSP API 파일들에서 사용하는 통합 데이터 저장 경로
     */
    public String getDataBasePath(ServletContext application) {
        String basePath = application.getRealPath("/");
        return basePath + File.separator + "data";
    }
}

// FileUtils 인스턴스 생성
FileUtils fileUtils = new FileUtils();



// 파일 크기 포맷팅 함수
public String formatFileSize(long bytes) {
    if (bytes < 1024) return bytes + " B";
    int exp = (int) (Math.log(bytes) / Math.log(1024));
    String pre = "KMGTPE".charAt(exp - 1) + "";
    return String.format("%.1f %sB", bytes / Math.pow(1024, exp), pre);
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/api/utils/FileUtils.jsp", Long.valueOf(1754455268926L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.google.gson");
    _jspx_imports_packages.add("java.nio.file");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

/**
 * CMS AI 사이트 목록 조회 API
 * GET 요청으로 생성된 모든 사이트 목록을 조회
 * 
 * Parameters:
 * - includeStats: 사이트별 통계 포함 여부 (true/false) - 기본값: false
 * - includeSiteInfo: 사이트 정보 포함 여부 (true/false) - 기본값: true
 * - sortBy: 정렬 기준 ('name', 'created', 'modified', 'size') - 기본값: 'name'
 * - order: 정렬 순서 ('asc', 'desc') - 기본값: 'asc'
 */

response.setContentType("application/json; charset=UTF-8");
response.setHeader("Access-Control-Allow-Origin", "*");
response.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
response.setHeader("Access-Control-Allow-Headers", "Content-Type");

// OPTIONS 요청 처리 (CORS preflight)
if ("OPTIONS".equals(request.getMethod())) {
    response.setStatus(HttpServletResponse.SC_OK);
    return;
}

try {
    // GET 요청만 허용
    if (!"GET".equals(request.getMethod())) {
        out.print(fileUtils.createErrorResponse("잘못된 요청 방식", "GET 요청만 허용됩니다."));
        return;
    }
    
    // 파라미터 수집
    String includeStatsParam = request.getParameter("includeStats");
    String includeSiteInfoParam = request.getParameter("includeSiteInfo");
    String sortBy = request.getParameter("sortBy");
    String order = request.getParameter("order");
    
    // 기본값 설정
    boolean includeStats = "true".equals(includeStatsParam);
    boolean includeSiteInfo = includeSiteInfoParam == null || !"false".equals(includeSiteInfoParam);
    if (sortBy == null || sortBy.trim().isEmpty()) {
        sortBy = "name";
    }
    if (order == null || order.trim().isEmpty()) {
        order = "asc";
    }
    
    // final 변수로 복사 (익명 클래스에서 사용하기 위해)
    final String finalSortBy = sortBy;
    final String finalOrder = order;
    final boolean finalIncludeStats = includeStats;
    
    // 사이트 목록 조회
    List<String> siteIds = fileUtils.listSites(application);
    List<Map<String, Object>> sitesData = new ArrayList<>();
    
    for (String siteId : siteIds) {
        Map<String, Object> siteData = new HashMap<>();
        siteData.put("siteId", siteId);
        
        String sitePath = fileUtils.getSitePath(application, siteId);
        
        // 사이트 정보 포함
        if (includeSiteInfo) {
            String siteInfoPath = sitePath + File.separator + "site-info.json";
            Map<String, Object> siteInfo = fileUtils.readJsonFile(siteInfoPath);
            if (siteInfo != null) {
                siteData.put("siteInfo", siteInfo);
                siteData.put("siteName", siteInfo.get("siteName"));
                siteData.put("domain", siteInfo.get("domain"));
                siteData.put("createdAt", siteInfo.get("createdAt"));
                siteData.put("lastUpdated", siteInfo.get("lastUpdated"));
            }
        }
        
        // 기본 폴더 정보
        File siteDir = new File(sitePath);
        if (siteDir.exists()) {
            siteData.put("lastModified", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
                .format(new Date(siteDir.lastModified())));
        }
        
        // 통계 정보 포함
        if (includeStats) {
            Map<String, Object> stats = new HashMap<>();
            
            // 메뉴 수 계산
            List<String> menus = fileUtils.listMenus(application, siteId);
            stats.put("totalMenus", menus.size());
            
            // 총 페이지 수 계산
            int totalPages = 0;
            for (String menuId : menus) {
                String menuPath = sitePath + File.separator + menuId;
                File menuDir = new File(menuPath);
                if (menuDir.exists() && menuDir.isDirectory()) {
                    File[] submenuDirs = menuDir.listFiles();
                    if (submenuDirs != null) {
                        // 디렉토리만 카운트 (File::isDirectory 대신 전통적인 방식 사용)
                        for (File f : submenuDirs) {
                            if (f.isDirectory()) {
                                totalPages++;
                            }
                        }
                    }
                }
            }
            stats.put("totalPages", totalPages);
            
            // 폴더 크기
            long siteSize = fileUtils.calculateDirectorySize(sitePath);
            stats.put("totalSize", siteSize);
            stats.put("totalSizeFormatted", formatFileSize(siteSize));
            
            siteData.put("stats", stats);
        }
        
        sitesData.add(siteData);
    }
    
    // 정렬 적용 (람다 대신 전통적인 Comparator 사용)
    Collections.sort(sitesData, new Comparator<Map<String, Object>>() {
        public int compare(Map<String, Object> a, Map<String, Object> b) {
            int result = 0;
            
            switch (finalSortBy.toLowerCase()) {
                case "name":
                    String nameA = (String) a.get("siteId");
                    String nameB = (String) b.get("siteId");
                    result = nameA.compareToIgnoreCase(nameB);
                    break;
                    
                case "created":
                    if (a.get("siteInfo") != null && b.get("siteInfo") != null) {
                        Map<String, Object> infoA = (Map<String, Object>) a.get("siteInfo");
                        Map<String, Object> infoB = (Map<String, Object>) b.get("siteInfo");
                        String createdA = (String) infoA.get("createdAt");
                        String createdB = (String) infoB.get("createdAt");
                        if (createdA != null && createdB != null) {
                            result = createdA.compareTo(createdB);
                        }
                    }
                    break;
                    
                case "modified":
                    String modifiedA = (String) a.get("lastModified");
                    String modifiedB = (String) b.get("lastModified");
                    if (modifiedA != null && modifiedB != null) {
                        result = modifiedA.compareTo(modifiedB);
                    }
                    break;
                    
                case "size":
                    if (finalIncludeStats) {
                        Map<String, Object> statsA = (Map<String, Object>) a.get("stats");
                        Map<String, Object> statsB = (Map<String, Object>) b.get("stats");
                        if (statsA != null && statsB != null) {
                            Long sizeA = ((Number) statsA.get("totalSize")).longValue();
                            Long sizeB = ((Number) statsB.get("totalSize")).longValue();
                            result = Long.compare(sizeA, sizeB);
                        }
                    }
                    break;
            }
            
            return "desc".equals(finalOrder) ? -result : result;
        }
    });
    
    // 응답 데이터 구성
    Map<String, Object> responseData = new HashMap<>();
    responseData.put("sites", sitesData);
    responseData.put("totalSites", sitesData.size());
    responseData.put("sortBy", sortBy);
    responseData.put("order", order);
    responseData.put("includeStats", includeStats);
    responseData.put("includeSiteInfo", includeSiteInfo);
    
    // 전체 통계
    if (includeStats) {
        Map<String, Object> globalStats = new HashMap<>();
        long totalSize = 0;
        int totalPages = 0;
        int totalMenus = 0;
        
        for (Map<String, Object> site : sitesData) {
            Map<String, Object> stats = (Map<String, Object>) site.get("stats");
            if (stats != null) {
                totalSize += ((Number) stats.get("totalSize")).longValue();
                totalPages += ((Number) stats.get("totalPages")).intValue();
                totalMenus += ((Number) stats.get("totalMenus")).intValue();
            }
        }
        
        globalStats.put("totalSize", totalSize);
        globalStats.put("totalSizeFormatted", formatFileSize(totalSize));
        globalStats.put("totalPages", totalPages);
        globalStats.put("totalMenus", totalMenus);
        globalStats.put("averagePagesPerSite", sitesData.size() > 0 ? (double) totalPages / sitesData.size() : 0);
        
        responseData.put("globalStats", globalStats);
    }
    
    // 성공 응답
    out.print(fileUtils.createSuccessResponse("사이트 목록 조회 성공", responseData));
    
} catch (Exception e) {
    // 예외 처리
    StringWriter sw = new StringWriter();
    PrintWriter pw = new PrintWriter(sw);
    e.printStackTrace(pw);
    String stackTrace = sw.toString();
    
    System.err.println("list-sites.jsp 오류: " + e.getMessage());
    System.err.println("Stack trace: " + stackTrace);
    
    out.print(fileUtils.createErrorResponse("서버 내부 오류", 
        "사이트 목록 조회 중 오류가 발생했습니다: " + e.getMessage()));
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
